Repository weaviate/weaviate, pull requests merged in 2018-10, with the labels that each got.

#523 gh-521: Add Error array
  models/error_response.go
  openapi-specs/schema.json
  restapi/configure_weaviate.go
  restapi/configure_weaviate_test.go
  restapi/embedded_spec.go
Labels: Core implementation

#531 gh-524: minor textual updates to the schema
  client/actions/actions_client.go
  client/things/things_client.go
  client/things/weaviate_things_properties_update_responses.go
  openapi-specs/schema.json
  restapi/embedded_spec.go
  restapi/operations/actions/weaviate_actions_properties_create.go
  restapi/operations/actions/weaviate_actions_properties_delete.go
  restapi/operations/things/weaviate_things_properties_create.go
  restapi/operations/things/weaviate_things_properties_delete.go
  restapi/operations/things/weaviate_things_properties_update_responses.go
Labels: enhancement

#544 [Don't merge yet please] Revert "gh-528: Split configure file in readable chunks"
  restapi/configure_weaviate.go
  restapi/configure_weaviate_actions.go
  restapi/configure_weaviate_graphql.go
  restapi/configure_weaviate_helpers.go
  restapi/configure_weaviate_keys.go
  restapi/configure_weaviate_keys_helpers.go
  restapi/configure_weaviate_things.go
  restapi/configure_weaviate_things_helpers.go
Labels: discussion
