Repository weaviate/weaviate, pull requests merged in 2025-09, with the labels that each got.

#9122 refact(memberlist-raft): remove locks to avoid lock contention
  cluster/resolver/raft.go
  cluster/store.go
  cluster/store_cluster_rpc.go
  usecases/cluster/state.go
Labels: reliability, zero-impact-rollouts

#9117 fix(raft): joiner was checking for wrong status code
  cluster/bootstrap/bootstrap_test.go
  cluster/bootstrap/joiner.go
  cluster/rpc/server.go
  cluster/rpc/server_test.go
Labels: reliability, zero-impact-rollouts

#9192 fix(alias): backup recovery error when using alias + overwrite_alias flag
  test/acceptance/aliases/aliases_api_backup_test.go
  tools/dev/run_dev_server.sh
  usecases/schema/class.go
Labels: community

#9134 fix(replication-broadcast): communicate failed broadcast to commit to avoid lost writes
  usecases/replica/coordinator.go
  usecases/replica/replicator_stream.go
Labels: reliability, zero-impact-rollouts

#9064 fix(raft-transport): avoid invalid ports to avoid rollout errors and tweak memberlist config
  adapters/handlers/rest/configure_api.go
  cluster/bootstrap/bootstrap.go
  cluster/bootstrap/joiner.go
  cluster/resolver/raft.go
  cluster/resolver/types.go
  cluster/rpc/server.go
  test/acceptance/recovery/network_isolation_test.go
  usecases/cluster/mocks/node_selector.go
  usecases/cluster/state.go
Labels: reliability, zero-impact-rollouts

#9200 fix(memberlist-raft) gracefully leave on shutdown and raft shutdown order
  cluster/raft_test.go
  cluster/store.go
  usecases/cluster/delegate_test.go
  usecases/cluster/log_workaround.go
  usecases/cluster/mocks/node_selector.go
  usecases/cluster/state.go
Labels: reliability, zero-impact-rollouts

#9235 fix(raft): pass local node name and address to store to use it in discovery
  cluster/resolver/types.go
  cluster/store.go
Labels: reliability, zero-impact-rollouts

#8997 fix(raft): joiner avoid self join dials
  cluster/bootstrap/joiner.go
  cluster/bootstrap/joiner_test.go
Labels: reliability, zero-impact-rollouts

#9242 chore(log): improve log current leader on leader found
  cluster/store.go
Labels: reliability, zero-impact-rollouts

#9254 fix(RAFT-memberlist): default RAFT_TIMEOUTS_MULTIPLIER to 5 to handle heavy load environments
  test/docker/weaviate.go
  usecases/config/environment.go
Labels: reliability, zero-impact-rollouts

#9260 refact(memberlist-config): re-name env var to MEMBERLIST_FAST_FAILURE_DETECTION
  test/acceptance/replication/read_repair/scale_test.go
  test/docker/docker.go
  test/docker/weaviate.go
  usecases/cluster/state.go
  usecases/config/environment.go
Labels: reliability, zero-impact-rollouts

#9280 feature: RoaringSet as default strategy for dimensions bucket
  adapters/repos/db/crud_references_integration_test.go
  adapters/repos/db/helpers/helpers.go
  adapters/repos/db/index.go
  adapters/repos/db/lsmkv/bucket.go
  adapters/repos/db/lsmkv/bucket_integration_test.go
  adapters/repos/db/lsmkv/commitlogger_parser_collection.go
  adapters/repos/db/lsmkv/commitlogger_parser_replace.go
  adapters/repos/db/lsmkv/commitlogger_parser_roaring_set.go
  adapters/repos/db/lsmkv/commitlogger_parser_strategy.go
  adapters/repos/db/lsmkv/commitlogger_parser_strategy_integration_test.go
  adapters/repos/db/lsmkv/segmentindex/strategies.go
  adapters/repos/db/lsmkv/testdata/strategy/inverted/segment-1757433233549050000.wal
  adapters/repos/db/lsmkv/testdata/strategy/inverted/segment-1757673130782244000.db
  adapters/repos/db/lsmkv/testdata/strategy/mapcollection/segment-1757496219190885000.wal
  adapters/repos/db/lsmkv/testdata/strategy/mapcollection/segment-1757605013813574000.db
  adapters/repos/db/lsmkv/testdata/strategy/replace/segment-1757496896327170000.wal
  adapters/repos/db/lsmkv/testdata/strategy/replace/segment-1757605006102787000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757433233551248000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757496903516930000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757605013811353000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757605013812425000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringsetrange/segment-1757496903517104000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringsetrange/segment-1757605013813462000.db
  adapters/repos/db/lsmkv/testdata/strategy/setcollection/segment-1757433233550212000.wal
  adapters/repos/db/lsmkv/testdata/strategy/setcollection/segment-1757605013815208000.db
  adapters/repos/db/mock_shard_like.go
  adapters/repos/db/node_wide_metrics.go
  adapters/repos/db/shard.go
  adapters/repos/db/shard_dimension_tracking.go
  adapters/repos/db/shard_dimension_tracking_test.go
  adapters/repos/db/shard_init_properties.go
  adapters/repos/db/shard_lazyloader.go
  adapters/repos/db/shard_write_inverted_lsm.go
Labels: 1.32

#9283 feature: RoaringSet as default strategy for dimensions bucket
  adapters/repos/db/lsmkv/bucket.go
  adapters/repos/db/lsmkv/bucket_integration_test.go
  adapters/repos/db/lsmkv/commitlogger_parser_collection.go
  adapters/repos/db/lsmkv/commitlogger_parser_replace.go
  adapters/repos/db/lsmkv/commitlogger_parser_roaring_set.go
  adapters/repos/db/lsmkv/commitlogger_parser_strategy.go
  adapters/repos/db/lsmkv/commitlogger_parser_strategy_integration_test.go
  adapters/repos/db/lsmkv/segmentindex/strategies.go
  adapters/repos/db/lsmkv/testdata/strategy/inverted/segment-1757433233549050000.wal
  adapters/repos/db/lsmkv/testdata/strategy/inverted/segment-1757673130782244000.db
  adapters/repos/db/lsmkv/testdata/strategy/mapcollection/segment-1757496219190885000.wal
  adapters/repos/db/lsmkv/testdata/strategy/mapcollection/segment-1757605013813574000.db
  adapters/repos/db/lsmkv/testdata/strategy/replace/segment-1757496896327170000.wal
  adapters/repos/db/lsmkv/testdata/strategy/replace/segment-1757605006102787000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757433233551248000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757496903516930000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757605013811353000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringset/segment-1757605013812425000.db
  adapters/repos/db/lsmkv/testdata/strategy/roaringsetrange/segment-1757496903517104000.wal
  adapters/repos/db/lsmkv/testdata/strategy/roaringsetrange/segment-1757605013813462000.db
  adapters/repos/db/lsmkv/testdata/strategy/setcollection/segment-1757433233550212000.wal
  adapters/repos/db/lsmkv/testdata/strategy/setcollection/segment-1757605013815208000.db
  adapters/repos/db/shard_dimension_tracking.go
  adapters/repos/db/shard_init_properties.go
  adapters/repos/db/shard_write_inverted_lsm.go
Labels: 1.31
